package toolkit

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"
)

var slugRe = regexp.MustCompile(`[^a-z0-9]+`)

// Slugify turns an arbitrary customer name into a DNS-safe slug.
func Slugify(s string) string {
	s = strings.ToLower(strings.TrimSpace(s))
	s = slugRe.ReplaceAllString(s, "-")
	return strings.Trim(s, "-")
}

// BuildConfig renders a ServiceConfig from customer parameters.
func BuildConfig(c Customer) ServiceConfig {
	if c.Slug == "" {
		c.Slug = Slugify(c.Name)
	}
	if c.Port == 0 {
		c.Port = 8080
	}
	if c.Replicas == 0 {
		c.Replicas = 2
	}
	if c.Environment == "" {
		c.Environment = "staging"
	}
	if c.Region == "" {
		c.Region = "us-east-1"
	}
	if c.Tier == "" {
		c.Tier = "standard"
	}
	svc := fmt.Sprintf("%s-sample-svc", c.Slug)
	return ServiceConfig{
		Customer:    c,
		ServiceName: svc,
		Image:       fmt.Sprintf("ghcr.io/maddoxk/sample-svc:%s", c.Tier),
		GeneratedAt: time.Now().UTC(),
		Endpoints: Endpoints{
			Health:  "/healthz",
			Ready:   "/readyz",
			Metrics: "/metrics",
			API:     "/api/v1/echo",
		},
	}
}

// Scaffold writes the rendered config plus a runnable sample-service main.go
// into outDir. It returns the resolved ServiceConfig.
func Scaffold(c Customer, outDir string) (ServiceConfig, error) {
	cfg := BuildConfig(c)
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return cfg, err
	}
	data, err := json.MarshalIndent(cfg, "", "  ")
	if err != nil {
		return cfg, err
	}
	if err := os.WriteFile(filepath.Join(outDir, "service.config.json"), data, 0o644); err != nil {
		return cfg, err
	}
	yaml := renderManifest(cfg)
	if err := os.WriteFile(filepath.Join(outDir, "deploy.yaml"), []byte(yaml), 0o644); err != nil {
		return cfg, err
	}
	if err := os.WriteFile(filepath.Join(outDir, "sample_service.go.txt"), []byte(sampleServiceSource), 0o644); err != nil {
		return cfg, err
	}
	return cfg, nil
}

func renderManifest(cfg ServiceConfig) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# Generated by fdetk for customer %q\n", cfg.Customer.Name)
	fmt.Fprintf(&b, "apiVersion: apps/v1\nkind: Deployment\nmetadata:\n")
	fmt.Fprintf(&b, "  name: %s\n  labels:\n    customer: %s\n    env: %s\n    tier: %s\n",
		cfg.ServiceName, cfg.Customer.Slug, cfg.Customer.Environment, cfg.Customer.Tier)
	fmt.Fprintf(&b, "spec:\n  replicas: %d\n  template:\n    spec:\n      containers:\n",
		cfg.Customer.Replicas)
	fmt.Fprintf(&b, "        - name: %s\n          image: %s\n          ports:\n            - containerPort: %d\n",
		cfg.ServiceName, cfg.Image, cfg.Customer.Port)
	fmt.Fprintf(&b, "          env:\n            - name: REGION\n              value: %s\n", cfg.Customer.Region)
	fmt.Fprintf(&b, "          livenessProbe:\n            httpGet:\n              path: %s\n              port: %d\n",
		cfg.Endpoints.Health, cfg.Customer.Port)
	fmt.Fprintf(&b, "          readinessProbe:\n            httpGet:\n              path: %s\n              port: %d\n",
		cfg.Endpoints.Ready, cfg.Customer.Port)
	return b.String()
}

// sampleServiceSource is emitted as a reference artifact; the in-process server
// in service.go is what actually runs during `deploy`.
const sampleServiceSource = `// Reference sample service emitted by fdetk scaffold.
package main

import (
	"encoding/json"
	"net/http"
)

func main() {
	http.HandleFunc("/healthz", func(w http.ResponseWriter, r *http.Request) {
		json.NewEncoder(w).Encode(map[string]string{"status": "ok"})
	})
	http.HandleFunc("/readyz", func(w http.ResponseWriter, r *http.Request) {
		json.NewEncoder(w).Encode(map[string]string{"ready": "true"})
	})
	http.ListenAndServe(":8080", nil)
}
`
